# Generated by Django 3.1.7 on 2021-05-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
